### ISSUE TITLE
Coypu 2.14, Selenium Grid 3.6.0, BrowserSession.Visit("url") throws "Missing 'handle' parameter"

### ISSUE THREAD

**Issue by jefflomax** [featurist/coypu#174]
FireFox 56, GeckoDriver 0.16.1, Selenium Grid 3.6.0 (selenium-server-standalone-3.6.0.jar)

Created a RemoteWebDriver pointed at the Selenium Hub, driver created fine.

Calling browser.Visit("url") called into SeleniumWindowManager.cs::SwitchToWindow(string windowName)
passing what looked like a window handle, "4294967297"
called webDriver.SwitchTo().Window(windowName); 

and crashed with "Missing 'handle' parameter"

This same call worked fine with Selenium Grid 2 (selenium-server-standalone-2.53.1.jar, FireFox 46).

Note: Using Chrome worked, but each FillIn() call sends XPATH that returns no results when running in Selenium Grid, which is likely this issue
https://groups.google.com/forum/#!topic/coypu/40FTL22WWmc

System.InvalidOperationException occurred
  HResult=0x80131509
  Message=Missing 'handle' parameter
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:40.131Z'
System info: host: 'SeleniumGridServer', ip: '142.136.xxx.xxx', os.name: 'Windows Server 2012 R2', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_144'
Driver info: driver.version: unknown (61)
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteTargetLocator.Window(String windowHandleOrName)
   at Coypu.Drivers.Selenium.SeleniumWindowManager.SwitchToWindow(String windowName) in V:\github\coypu-master\src\Coypu\Drivers\Selenium\SeleniumWindowManager.cs:line 44
   at Coypu.Drivers.Selenium.SeleniumWindow.SwitchTo(String windowName) in V:\github\coypu-master\src\Coypu\Drivers\Selenium\SeleniumWindow.cs:line 89
   at Coypu.Drivers.Selenium.SeleniumWindow.get_Native() in V:\github\coypu-master\src\Coypu\Drivers\Selenium\SeleniumWindow.cs:line 82
   at Coypu.Drivers.Selenium.ElementFinder.SeleniumScope(Scope scope) in V:\github\coypu-master\src\Coypu\Drivers\Selenium\ElementFinder.cs:line 24
   at Coypu.Drivers.Selenium.SeleniumWebDriver.Visit(String url, Scope scope) in V:\github\coypu-master\src\Coypu\Drivers\Selenium\SeleniumWebDriver.cs:line 126
   at Coypu.BrowserWindow.Visit(String virtualPath) in V:\github\coypu-master\src\Coypu\BrowserWindow.cs:line 69
   at WorkforceTestSuite.Common.BrowserSessionExtensions.WFLogin(BrowserSession browser, String companySelection) in C:\Sandboxes\WorkforceGit\WorkforceTestSuite\Common\BrowserSessionExtensions.cs:line 56
   at WorkforceTestSuite.Tests.Workforce.GeneralSetup.SitesTest.Sites_edit() in C:\Sandboxes\WorkforceGit\WorkforceTestSuite\Tests\Workforce\GeneralSetup\SitesTest.cs:line 33

Selenium Grid configuration

java -jar %SELENIUM_STANDALONE% -role hub -hubConfig hubConfig.json
hubConfig.json:
{
  "_comment" : "Configuration for Hub - hubConfig.json",
  "host": ip,
  "maxSessions": 5,
  "port": 4444,
  "cleanupCycle": 5000,
  "timeout": 300000,
  "newSessionWaitTimeout": -1,
  "servlets": [],
  "prioritizer": null,
  "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
  "throwOnCapabilityNotPresent": true,
  "nodePolling": 180000,
  "platform": "WINDOWS"
}

java -Dwebdriver.gecko.driver="%CD%\geckodriver.exe" -Dwebdriver.chrome.driver="%CD%\chromedriver.exe" -jar %SELENIUM_STANDALONE% -role node -hub http://%COMPUTERNAME%:4444/grid/register -nodeConfig nodeConfig.json
nodeConfig.json:
{
  "capabilities":
  [
    {
      "browserName": "chrome",
      "maxInstances": 5,
      "seleniumProtocol": "WebDriver"
    },
    {
      "browserName": "internet explorer",
      "maxInstances": 1,
      "seleniumProtocol": "WebDriver"
    },
    {
      "browserName": "firefox",
      "maxInstances": 5,
      "seleniumProtocol": "WebDriver"
    }
  ],
  "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
  "maxSession": 5,
  "port": 5555,
  "register": true,
  "registerCycle": 5000,
  "hub": "http://localhost:4444",
  "nodeStatusCheckTimeout": 5000,
  "nodePolling": 5000,
  "role": "node",
  "unregisterIfStillDownAfter": 60000,
  "downPollingLimit": 2,
  "debug": false,
  "servlets" : [],
  "withoutServlets": [],
  "custom": {}
}

**Comment by alexlazarciuc** [comment]
Hey @jefflomax,

I'm facing the same issue when I try to run the tests remote on BrowserStack by using Coypu BrowserSession instance. However, if I user RemoteWebDriver instance it works perfectly fine.
Also, to mention the fact that running on local Coypu BrowserSession works perfectly fine, and I am able to Visit(pageUrl), when running on BrowserStack I get: 
An exception of type 'System.InvalidOperationException' occurred in WebDriver.dll but was not handled in user code
Additional information: Missing 'handle' parameter
Build info: version: '3.8.0', revision: '924c4067df', time: '2017-11-30T11:37:19.049Z'
System info: host: '185-129-69-133', ip: '185.129.69.133', os.name: 'windows', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_151'
Driver info: driver.version: unknown (61)

**Comment by alexlazarciuc** [comment]
Hey folks,

This is fixed now with latest Selenium version. The tests run fine in Browserstack and local.
