### ISSUE TITLE
 Acceptdilogue() method is not working on IE11 with coypu 2.14.0 version.

### ISSUE THREAD

**Issue by BTallapragada** [featurist/coypu#184]
Model Dialogue getting auto cancelled (closing automatically without and actionfrom the script) on IE11 and then throwing the following exception.

Coypu.MissingDialogException : No dialog was present to accept
  ----> OpenQA.Selenium.NoAlertPresentException : No alert is active
   at Coypu.Timing.RetryUntilTimeoutTimingStrategy.SynchroniseTResult
   at Coypu.BrowserWindow.AcceptModalDialog(Options options)
 -NoAlertPresentException
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteTargetLocator.Alert()
   at Coypu.Drivers.Selenium.Dialogs.AcceptModalDialog()

**Comment by obstar** [comment]
if dialog is auto cancelled remove step from your test where coypu try to close it
